[build]
target = "./x86_64-unknown-dragonos.json"
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-no-pie",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]